---
- name: install Fluentd
  become: yes
  hosts: 175.0.0.172
  tasks:
    - name: creating enviroment for fluentd
      become: yes
      copy:
        dest: /etc/sysctl.conf
        content: |
          net.core.somaxconn = 1024
          net.core.netdev_max_backlog = 5000
          net.core.rmem_max = 16777216
          net.core.wmem_max = 16777216
          net.ipv4.tcp_wmem = 4096 12582912 16777216
          net.ipv4.tcp_rmem = 4096 12582912 16777216
          net.ipv4.tcp_max_syn_backlog = 8096
          net.ipv4.tcp_slow_start_after_idle = 0
          net.ipv4.tcp_tw_reuse = 1
          net.ipv4.ip_local_port_range = 10240 65535
          # If forward uses port 24224, reserve that port number for use as an ephemeral
port.
          # # If another port, e.g., monitor_agent uses port 24220, add a comma-separated
 list of port numbers.
          # # net.ipv4.ip_local_reserved_ports = 24220,24224
          net.ipv4.ip_local_reserved_ports = 24224
    - name: apply sysctl.conf
      become: yes
      shell: |
        sysctl -p
        curl -fsSL https://toolbelt.treasuredata.com/sh/install-amazon2023-fluent-package
5-lts.sh | sh
    - name: updating fluentd.conf
      become: yes
      blockinfile:
        path: /etc/fluent/fluentd.conf
        block: |
          <source>
           @type kafka
           brokers kafka1:9092,kafka2:9092,kafka3:9092
           topics chatbot-log
           format json
          </source>
          <source>
           @type kafka
           brokers kafka1:9092,kafka2:9092,kafka3:9092
           topics crawler-log-data
           format json
          </source>
          <source>
           @type kafka
           brokers kafka1:9092,kafka2:9092,kafka3:9092
           topics crawling-log
           format json
          </source>
		  <source>
           @type kafka
           brokers kafka1:9092,kafka2:9092,kafka3:9092
           topics job-data
           format none
          </source>
          <source>
           @type kafka
           brokers kafka1:9092,kafka2:9092,kafka3:9092
           topics embedding-log
           format json
          </source>
          <match crawler-job-data>
           @type opensearch
           hosts https://search-log-dashboard-test-w4f7q7bjqugb4kioyxjj362m6u.ap-northeas
t-2.es.amazonaws.com
           port 443
           user kafka-sesac
           password Sesac230828!
           index_name crawler-job-data
           logstash_format false
          </match>
          <match embedding-log>
           @type opensearch
           hosts https://search-log-dashboard-test-w4f7q7bjqugb4kioyxjj362m6u.ap-northeas
t-2.es.amazonaws.com
           port 443
           user kafka-sesac
           password Sesac230828!
           index_name embedding-log
           logstash_format false
          </match>
          <match chatbot-log>
           @type opensearch
           hosts https://search-log-dashboard-test-w4f7q7bjqugb4kioyxjj362m6u.ap-northeas
t-2.es.amazonaws.com
           port 443
           user kafka-sesac
           password Sesac230828!
           index_name chatbot-log
           logstash_format false
          </match>
          <match crawling-log>
           @type opensearch
           hosts https://search-log-dashboard-test-w4f7q7bjqugb4kioyxjj362m6u.ap-northeas
t-2.es.amazonaws.com
           port 443
           user kafka-sesac
           password Sesac230828!
           index_name crawling-log
           logstash_format false
          </match>
          <match job-data>
           @type s3
           s3_bucket project05-crawling
		   region ap-northeast-2
           path job-data/
           store_as text
           <buffer>
            timekey 60
           </buffer>
           <format>
            @type single_value
           </format>
          </match>
    - name: start fluentd.service
      become: yes
      service:
       name: fluentd
       state: started
       enabled: yes

