kafka-install.yaml
---
- name: Kafka Zookeeper Install
  hosts: kafkaservers
  become: yes
  vars:
    - installation_dir: /opt/kafka
  tasks:
    - name: install JDK 11
      yum:
       name: java-11-amazon-corretto.x86_64
       state: present
    - name: create a group
      group:
        name: kafka
        state: present
    - name: create a user
      user:
        name: kafka
        state: present
        group: kafka
    - name: Create a Directory
      become: yes
      shell: |
        mkdir -p /opt/kafka | chown kafka: /opt/kafka
		mkdir -p /opt/promethus | chown kafka: /opt/pormethus
    - name: download JMX Exporter
      copy:
        src: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.
19.0/jmx_prometheus_javaagent-0.19.0.jar
        dest: "{{installation_dir}}/promethus"
        remote_src: yes
    - name: download kafka_2_0_0.yaml
      copy:
        src: https://raw.githubusercontent.com/prometheus/jmx_exporter/master/example_con
figs/kafka-2_0_0.yml
        dest: "{{installation_dir}}/promethus"
    - name: download and unarchive zookeeper
      become: yes
      become_user: kafka
      unarchive:
       src: https://dlcdn.apache.org/zookeeper/zookeeper-3.8.3/apache-zookeeper-3.8.3-bin
.tar.gz
       dest: "{{installation_dir}}"
       mode: 0755
       remote_src: yes
    - name: download and unarchive kafka
      become: yes
      become_user: kafka
      unarchive:
        src: https://archive.apache.org/dist/kafka/2.8.2/kafka_2.13-2.8.2.tgz
        dest: "{{installation_dir}}"
        mode: 0755
        remote_src: yes
    - name: create a link
      become: yes
      become_user: kafka
      shell: |
       cd /opt/kafka
       ln -s apache-zookeeper-3.8.3-bin zookeeper
       ln -s kafka_2.13-2.8.2 kafka
       echo "export PATH=$PATH:/opt/kafka/zookeeper/bin:/opt/kafka/kafka/bin" | tee -a ~/
.bash_profile > /dev/null
       source ~/.bash_profile
    - name: Create a service for zookeeper
      copy:
       dest: /etc/systemd/system/zookeeper.service
       content: |
        [Unit]
        Description=Zookeeper Daemon
        Documentation=https://zookeeper.apache.org
        Requires=network.target
        After=network.target

        [Service]
        Type=forking
        WorkingDirectory={{installation_dir}}/zookeeper
        User=root
        Group=root
        ExecStart={{installation_dir}}/zookeeper/bin/zkServer.sh start {{installation_dir
}}/zookeeper/conf/zoo.cfg
        ExecStop={{installation_dir}}/zookeeper/bin/zkServer.sh stop {{installation_dir}}
/zookeeper/conf/zoo.cfg
        ExecReload={{installation_dir}}/zookeeper/bin/zkServer.sh restart {{installation_
dir}}/zookeeper/conf/zoo.cfg
        TimeoutSec=10
        Restart=on-abnormal
        [Install]
        WantedBy=default.target
    - name: Create a service for kafka
      copy:
       dest: /etc/systemd/system/kafka.service
       content: |
        [Unit]
        Description=Apache Kafka server (broker)
        Requires=network.target remote-fs.target zookeeper.service
        After=network.target remote-fs.target zookeeper.service
        [Service]
        Type=forking
        User=kafka
        Group=kafka
		Environment="KAFKA_OPTS=-javaagent:{{installation_dir}}/promethus/jmx_prometheus_
javaagent-0.19.0.jar=7071:{{installation_dir}}/promethus/kafka-2_0_0.yml"
        Environment='KAFKA_HEAP_OPTS=-Xms500m -Xmx500m'
        ExecStart={{installation_dir}}/kafka/bin/kafka-server-start.sh -daemon  {{install
ation_dir}}/kafka/config/server.properties
        ExecStop={{installation_dir}}/kafka/bin/kafka-server-stop.sh
        LimitNOFILE=16384:163840
        Restart=on-abnormal
        [Install]
        WantedBy=multi-user.target