---
- name: kafka update config
  hosts: kafkaservers
  become: yes
  vars:
    seq: "{{ groups.kafkaservers.index(inventory_hostname) + 1}}"
    zookeepers: "{{ groups.kafkaservers | join(':2181, ')}}:2181"
    installation_dir: /opt/kafka
  tasks:
   - name: update Broker ID
     become: yes
     become_user: kafka
     replace:
      path: "{{installation_dir}}/kafka/config/server.properties"
      regexp: 'broker.id=0'
      replace: 'broker.id={{seq}}'
      backup: yes
   - name: Update listeners
     become: yes
     become_user: kafka
     replace:
      path: "{{ installation_dir }}/kafka/config/server.properties"
      regexp: '#listeners=PLAINTEXT://:9092'
      replace: 'listeners=PLAINTEXT://:9092'
      backup: yes
   - name: Update advertiesd listeners
     become: yes
     become_user: kafka
     replace:
      path: "{{installation_dir}}/kafka/config/server.properties"
      regexp: '#advertiesd.listeners.+'
      replace: 'advertiesd.listeners=PLAINTEXT://{{ ansible_ens5.ipv4.address}}:9092'
      backup: yes
   - name: update zookeeper.server
     become: yes
     become_user: kafka
     replace:
      path: "{{installation_dir}}/kafka/config/server.properties"
      regexp: 'zookeeper.connect=.+'
      replace: 'zookeeper.connect={{ zookeepers }}'
      backup: yes
   - name: update zookeeper log dir
     become: yes
     become_user: kafka
     replace:
       path: "{{installation_dir}}/kafka/config/server.properties"
       regexp: 'log.dirs=/tmp/kafka-logs'
       replace: 'log.dirs={{installation_dir}}/kafka/logs'
       backup: yes
   - name: update zookeeper config
     become: yes
     become_user: kafka
     copy:
      dest: "{{installation_dir}}/zookeeper/conf/zoo.cfg"
      content: |
        dataDir=/opt/kafka/zookeeper/data
        clientPort=2181
        syncLimit=5
        initLimit=10
        tickTime=2000
        server.{{ item.0 + 1}}={{ item.1 }}:2888:3888
        admin.serverPort=8080
     with_indexed_items: "{{ groups.kafkaservers }}"
   - name: make zookeeper myid file
     become: yes
     become_user: kafka
     shell: |
      mkdir /opt/kafka/zookeeper/data && echo {{ seq }} > /opt/kafka/zookeeper/data/myid
   - name: zookeeper and kafka service start
     become: yes
     service:
       name: '{{ item }}'
       state: started
       enabled: yes
     with_items:
      - "kafka"
      - "zookeeper"